### ISSUE TITLE
Serving Static Icons

### ISSUE THREAD

**Issue by ChrisLightfootWild** [santimar/traefik-home#55]
:wave:

This is a great little project, I was looking for something to give myself a quick dev dashboard and this does the job nicely!

This might be something to add to the README if it's useful for anybody else, but I wanted to serve some static icons for some local projects.

This can be achieved by mounting them into the container if you already have them on the host filesystem in another checkout out repo, for example.

```yaml
    traefik-home:
        image: ghcr.io/santimar/traefik-home:v1.4.0
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - "/path/to/your/logo.svg:/usr/share/nginx/html/icons/my-mounted-logo.svg:ro"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.traefik-home.tls=true"
            - "traefik.http.routers.traefik-home.rule=Host(`dashboard.localhost`)"
```

You can then use 
```yaml
      - "traefik-home.icon=https://dashboard.localhost/icons/my-mounted-logo.svg"
```
